-- BUDDY Chat System Tables

-- Chat sessions table
CREATE TABLE IF NOT EXISTS buddy_chats (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Chat messages table
CREATE TABLE IF NOT EXISTS buddy_messages (
    id SERIAL PRIMARY KEY,
    chat_id INTEGER NOT NULL REFERENCES buddy_chats(id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role VARCHAR(20) NOT NULL, -- 'user' or 'assistant'
    content TEXT NOT NULL,
    metadata JSONB, -- Store context like skills used, documents referenced
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Uploaded documents for RAG
CREATE TABLE IF NOT EXISTS buddy_documents (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    file_name VARCHAR(255) NOT NULL,
    file_type VARCHAR(20) NOT NULL, -- 'pdf', 'docx', 'txt'
    file_url TEXT NOT NULL,
    extracted_text TEXT,
    file_size INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Document embeddings for vector similarity
CREATE TABLE IF NOT EXISTS buddy_embeddings (
    id SERIAL PRIMARY KEY,
    document_id INTEGER NOT NULL REFERENCES buddy_documents(id) ON DELETE CASCADE,
    chunk_index INTEGER NOT NULL,
    chunk_text TEXT NOT NULL,
    embedding vector(1536), -- OpenAI embedding dimension (if using pgvector)
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Extracted skills from documents/resume
CREATE TABLE IF NOT EXISTS buddy_extracted_skills (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    skill VARCHAR(100) NOT NULL,
    skill_category VARCHAR(50), -- 'technical', 'soft', 'domain'
    proficiency_level VARCHAR(20), -- 'beginner', 'intermediate', 'advanced', 'expert'
    source VARCHAR(50), -- 'resume', 'document', 'chat'
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Cover letters generated by BUDDY
CREATE TABLE IF NOT EXISTS buddy_cover_letters (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    job_title VARCHAR(255),
    company_name VARCHAR(255),
    content TEXT NOT NULL,
    generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Context memory for personalized guidance
CREATE TABLE IF NOT EXISTS buddy_context_memory (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    context_type VARCHAR(50), -- 'career_goal', 'learning_path', 'project_idea', 'interview_prep'
    context_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create indices for faster queries
CREATE INDEX IF NOT EXISTS idx_buddy_chats_user_id ON buddy_chats(user_id);
CREATE INDEX IF NOT EXISTS idx_buddy_messages_chat_id ON buddy_messages(chat_id);
CREATE INDEX IF NOT EXISTS idx_buddy_documents_user_id ON buddy_documents(user_id);
CREATE INDEX IF NOT EXISTS idx_buddy_embeddings_document_id ON buddy_embeddings(document_id);
CREATE INDEX IF NOT EXISTS idx_buddy_extracted_skills_user_id ON buddy_extracted_skills(user_id);
CREATE INDEX IF NOT EXISTS idx_buddy_context_memory_user_id ON buddy_context_memory(user_id);
